# Generated by Django 3.1.2 on 2022-02-18 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('member_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=30)),
                ('dob', models.DateField(default='dd/mm/yyyy')),
                ('occupation', models.CharField(choices=[('student', 'Student'), ('employee', 'Employed'), ('freelancer', 'Freelancer'), ('unenployed', 'Unemployed'), ('others', 'others')], default='choose', max_length=20)),
                ('phone', models.IntegerField()),
                ('address', models.CharField(max_length=300)),
                ('city', models.CharField(max_length=20)),
                ('state', models.CharField(choices=[('assam', 'Assam'), ('delhi', 'Delhi'), ('kolkata', ' Kolkata'), ('hyderabad', 'Hyderabad')], default='choose', max_length=15)),
                ('zip', models.IntegerField()),
                ('plan', models.CharField(choices=[('silver', 'Silver(1 month)'), ('gold', 'Gold(6 Months)'), ('diamond', 'Diamond(1 year)')], default='choose', max_length=40)),
                ('shift', models.CharField(choices=[('morning', 'Morning(5:00 am - 8:00 am)'), ('evening', 'Evening(4:00 am - 7:00 pm)')], default='choose', max_length=30)),
            ],
        ),
    ]
