# Generated by Django 3.1.2 on 2022-04-08 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='occupation',
            field=models.CharField(choices=[('Student', 'Student'), ('Employee', 'Employed'), ('Freelancer', 'Freelancer'), ('Unemployed', 'Unemployed'), ('others', 'others')], default='choose', max_length=20),
        ),
        migrations.AlterField(
            model_name='member',
            name='plan',
            field=models.CharField(choices=[('Silver(1 month)', 'Silver(1 month)'), ('Gold(6 Months)', 'Gold(6 Months)'), ('Diamond(1 year)', 'Diamond(1 year)')], default='choose', max_length=40),
        ),
        migrations.AlterField(
            model_name='member',
            name='shift',
            field=models.CharField(choices=[('Morning(5:00 am - 8:00 am)', 'Morning(5:00 am - 8:00 am)'), ('Evening(4:00 am - 7:00 pm)', 'Evening(4:00 am - 7:00 pm)')], default='choose', max_length=30),
        ),
        migrations.AlterField(
            model_name='member',
            name='state',
            field=models.CharField(choices=[('Assam', 'Assam'), ('Delhi', 'Delhi'), ('Kolkata', ' Kolkata'), ('Hyderabad', 'Hyderabad')], default='choose', max_length=15),
        ),
    ]
