# Generated by Django 3.1.2 on 2022-04-08 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20220408_1044'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='payment',
            field=models.IntegerField(default='0000'),
        ),
    ]
