# Generated by Django 3.1.2 on 2022-04-08 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_member_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='payment',
            field=models.IntegerField(),
        ),
    ]
