# Generated by Django 3.1.2 on 2022-04-08 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20220408_1139'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='payment',
        ),
    ]
