# Generated by Django 3.1.2 on 2022-04-08 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_remove_member_payment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipments',
            fields=[
                ('equi_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('category', models.CharField(choices=[('Free weights', 'Free weights'), ('Machines', 'Machines'), ('Racks', 'Racks')], default='choose', max_length=30)),
                ('quantity', models.IntegerField()),
            ],
        ),
    ]
